# Generated by Django 6.0 on 2026-01-22 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('wedding', 'Wedding'), ('birthday', 'Birthday'), ('corporate', 'Corporate'), ('other', 'Other')], max_length=50)),
                ('image_url', models.URLField(blank=True, help_text='External URL for the image')),
                ('image', models.ImageField(blank=True, help_text='Upload image (optional)', null=True, upload_to='events/')),
                ('features', models.TextField(blank=True, help_text='Features separated by newlines')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(help_text='Type of event (e.g. Wedding, Birthday)', max_length=100)),
                ('event_sub_type', models.CharField(blank=True, help_text='e.g. Mehendi, Haldi', max_length=100)),
                ('date', models.DateField()),
                ('venue', models.CharField(max_length=200)),
                ('additional_details', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
