# Generated by Django 6.0 on 2026-01-22 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('wedding', 'Wedding'), ('birthday', 'Birthday'), ('corporate', 'Corporate'), ('engagement', 'Engagement'), ('haldi', 'Haldi'), ('mehendi', 'Mehendi'), ('hindu_wedding', 'Hindu Wedding'), ('muslim_wedding', 'Muslim Wedding'), ('christian_wedding', 'Christian Wedding'), ('beach_wedding', 'Beach Wedding'), ('other', 'Other')], max_length=50),
        ),
    ]
